feat: Rename from sugar to core module name
osl-incubator/sugar pull request #101
Opened 2023-12-20 18:40 UTC by esloch

## Pull Request description

## How to test these changes

* ```...```

## Pull Request checklists

This PR is a:
- [ ] bug-fix
- [ ] new feature
- [ ] maintenance

About this PR:
- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more complexity.
- [ ] New and old tests passed locally.

## Additional information

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved .
```

2023-12-20 19:29 UTC, xmnlab requested changes

2023-12-20 19:29 UTC, xmnlab commented on src/sugar/cli.py
> +from core import Sugar
```suggestion
from sugar.core import Sugar
```

2023-12-20 19:29 UTC, xmnlab commented on src/sugar/core.py
> +from core import __version__
```suggestion
from sugar import __version__
```

2023-12-20 19:29 UTC, xmnlab commented on tests/test_containers_sugar.py
> +from core import Sugar
```suggestion
from sugar.core import Sugar
```

2023-12-21 15:37 UTC, xmnlab commented
@esloch I just merged this PR: https://github.com/osl-incubator/sugar/pull/102
could you rebase your branch on top of the upstream main?

2023-12-21 18:21 UTC, esloch commented
> @esloch I just merged this PR: #102 could you rebase your branch on top of the upstream main?

I think that we need to update the poetry.lock.

2023-12-22 00:44 UTC, esloch commented
> Could you remove and recreate it please?

I removed the "poetry.lock" and then run the "poetry update":

``` 
(sugar) ✔ /workspace/repos/osl/sugar [rename-module|● 1] 
21:39 $ poetry update
Updating dependencies
Resolving dependencies... (65.4s)

The current project's Python requirement (>=3.8.1) is not compatible with some of the required packages Python requirement:
  - makim requires Python >=3.8.1,<4.0.0, so it will not be satisfied for Python >=4.0.0

Because containers-sugar depends on makim (1.8.3) which requires Python >=3.8.1,<4.0.0, version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For makim, a possible solution would be to set the `python` property to ">=3.8.1,<4.0.0"
   ```

2023-12-22 02:12 UTC, xmnlab commented
@esloch the issue with the installation was fixed (I hope!)
now the error is about the tests.

2023-12-22 09:26 UTC, esloch commented
> @esloch the issue with the installation was fixed (I hope!) now the error is about the tests.

Thanks Ivan!

2023-12-24 00:32 UTC, xmnlab commented
@esloch , just cut a new release. please, rebase your branch on top of the upstream main

2024-01-15 12:03 UTC, merged